#!/usr/bin/env bash

GREY="\[\033[00m\]"
BLACK="\[\033[0;30m\]"
BLACKBOLD="\[\033[1;30m\]"
RED="\[\033[0;31m\]"
REDBOLD="\[\033[1;31m\]"
GREEN="\[\033[0;32m\]"
GREENBOLD="\[\033[1;32m\]"
YELLOW="\[\033[0;33m\]"
YELLOWBOLD="\[\033[1;33m\]"
BLUE="\[\033[0;34m\]"
BLUEBOLD="\[\033[1;34m\]"
PURPLE="\[\033[0;35m\]"
PURPLEBOLD="\[\033[1;35m\]"
CYAN="\[\033[0;36m\]"
CYANBOLD="\[\033[1;36m\]"
WHITE="\[\033[0;37m\]"
WHITEBOLD="\[\033[1;37m\]"

PS_USER=""
user=`whoami`
if [ "$user" == "root" ]
then
    PS_USER="$REDBOLD\u "
elif [ "$CONFIG_PROMPT_USER" != "$user" ]
then
    PS_USER="$GREENBOLD\u "
fi

PS_DIR="$BLUEBOLD\w\["

PS_END="$YELLOWBOLD \\$ "

export PS1="$PS_USER$PS_DIR$PS_END"
